version: '2'
volumes:
  map-decorator-db2:
  mapdecorator-photos:

services:
#  redis:
#    container_name: redis
#    image: redis:alpine
#    ports:
#     - "6380:6379"
  #  ptn_db-db:
  #    image: dmitryrck/dbeaver:latest
  #    container_name: ptn_db
  map_decorator_db:
    container_name: map_decorator_db
    volumes:
      - map-decorator-db2:/var/lib/mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=artifacts
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
  service:
    #build: .
    image: ornaments:12_02_2021
#    entrypoint: tail -f /dev/null
    depends_on:
      - map_decorator_db
    volumes:
      - ./service/target:/ornaments
      - mapdecorator-photos:/photos
    container_name: ornafuck
    #env_file: plugin.env
   # entrypoint: tail -F anything
    environment:
      - DATA_PATH=/plugin_path
#      - ENVIRONMENT=dev
    ports:
     - "6970:8080"
networks:
  default:
    external:
      name: map-decorator
