version: '2'
volumes:
  map-decorator-db2:
  mapdecorator-photos:

# map-decorator-1.creazehjbnoq.eu-central-1.rds.amazonaws.com
#AWS DB instance identifierInfo : map-decorator-1
# user : admin
# pass : k3cekmwqEtjA9eKS

services:
#  redis:
#    container_name: redis
#    image: redis:alpine
#    ports:
#     - "6380:6379"
  #  ptn_db-db:
  #    image: dmitryrck/dbeaver:latest
  #    container_name: ptn_db
  map_decorator_db:
    container_name: map_decorator_db
    volumes:
      - map-decorator-db2:/var/lib/mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=artifacts
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
  service:
    #build: .
    image: map-decorator-aws:v1
#    entrypoint: tail -f /dev/null
#    depends_on:
#      - map_decorator_db
    volumes:
      - ./service/target:/ornaments
      - mapdecorator-photos:/photos
    container_name: map-decorator-application
    #env_file: plugin.env
   # entrypoint: tail -F anything
    env_file:
      - conf.env
    ports:
     - "6970:8080"
networks:
  default:
    external:
      name: map-decorator
